#!/bin/env bash
#set -ex
DIR=~/.turbodl
if [ -d "$DIR" ]; then cd "$DIR"; fi
zip -rq turbo.zip * -x md5 -x *list
if [ -e mtoday.txt ]; then cat mtoday.txt > text; elif [ -e stoday.txt ]; then cat stoday.txt > text; fi
if [ ! -e md5 ]; then md5sum turbo.zip > md5; exit; fi
if [ $(md5sum turbo.zip | sed 's/  .*//') == $(grep 'turbo' md5 | sed 's/  .*//') ]; then
    exit
else
    sed -i "s/.*turbo.*/$(md5sum turbo.zip)/" md5
    if [ "$USER" == 'root' -o "$USER" == '' ]; then
        echo | mutt -s 'turbodlbot' -i text -a turbo.zip -- persie@turbodl.xyz
    fi
fi
