#!/bin/env bash
set -ex
DIR=~/.turbodl
if [ -d "$DIR" ]; then cd "$DIR"; fi
zip -rq turbo.zip * -x md5 -x *list -x junk/pid*
#if [ -e mtoday.txt ]; then cat mtoday.txt > text; elif [ -e stoday.txt ]; then cat stoday.txt > text; fi
#if [ -e mtoday.txt ]; then cat mtoday.txt > text; fi
#if [ -e lightdl.txt ]; then cat lightdl.txt >> text; elif [ -e twitchdl.txt ]; then cat twitchdl.txt >> text; fi
if [ "$USER" != 'persie' ]; then
    if [ -e results.txt ]; then
        echo | mutt -s 'turbodlbot' -i results.txt -a turbo.zip -- persie@turbodl.xyz
    else
        echo | mutt -s 'turbodlbot' -a turbo.zip -- persie@turbodl.xyz
    fi
fi
